In [2]:
import pandas as pd
import numpy as py

In [3]:
fpath1=r'C:\Users\刘佳琦\Desktop\待整理表格.xlsx'
df_1 = pd.read_excel(fpath1)

In [4]:
a=df_1['成员信息'][3].split('，')
#b=a.split(' ')
#df_1['成员信息'][3].split(' ')
' ' in df_1['成员信息'][0]

False

In [5]:
df_1['负责人姓名'][0]

'陈宇'

In [6]:
df_1.shape

(57, 3)

In [7]:
a=[]
for i in range(57):
    if '，' in df_1['成员信息'][i]:
        x=df_1['成员信息'][i].split('，')
        a.append(x)
    elif ' ' in  df_1['成员信息'][i]:
        x=df_1['成员信息'][i].split(' ')
        a.append(x)
    elif ',' in  df_1['成员信息'][i]:
        x=df_1['成员信息'][i].split(',')
        a.append(x) 

a

[['冯翊/1853850', '刘帅年/1851963'],
 ['寇蓝文/1853010', '王乐/1851929'],
 ['汪诗雨/1850847', '', '魏鹏程/1850001'],
 ['刘裕行/1851608', '', '赵启晨/1851878'],
 ['刘天元/1852971', '闫弘/1852571'],
 ['张笑寒/1853501', '尹长江/1850481'],
 ['周鹏/1853854', '肖启贤/1853361', ''],
 ['姚永锐/1851876', '', '徐晨龙/1854084'],
 ['陈璟赋/1851175', '孙思薇/1854171'],
 ['郭子淳/1852089', ''],
 ['刘佳明/1851626', '黄健/1854190'],
 ['张露颖/1853605', '周家旋/1854127'],
 ['王思澄/1853804', '袁宇童/1851615'],
 ['樊庶/1850630', '代贵淇/1853453'],
 ['周思琪/1853521', '杨雨辰/1853829'],
 ['潘帅鑫/1752221', '汤兆年/1752063'],
 ['曾宪坤/1852844', '姜梓恒/1853102'],
 ['徐子璇/1853838', '吴子豪/1752066'],
 ['余宁海/1951354', '张荣添/1952541', '梁雨萌/1953833'],
 ['胡启云/1952897', '', '钱璟怡/1952946'],
 ['张子阳1953437', '', '韦欢夏1953666', '', '沈梦竹1953248', '', '', '尹天硕1953350'],
 ['唐一淼/1953210', '唐宇瀚/1950152', '江宇睿/1953197', '王雨悦/1950172'],
 ['陶冶/1952066', '齐晓燕/1953907', '蓝天/1951609'],
 ['许灵辰/1954101', '张家瑞/1952241', '刘思睿/1953103', '李心瑜/1951242'],
 ['岳钊名/1953727', '卞宇轩/1953927', '李涛/1953107', '孙涵枫/1953955'],
 ['王子玮/1753387', '杨逢春/1751913', '郭浩/1853926'],
 ['加旺顿珠/1754297', '格桑/1754291', '萨米那/1754288', '格桑曲珍/1754305'],
 ['王普', '/1751148', '胡逸凡/1753180', '柏成/1752157'],
 ['董泽坤/1953768', '彭西哿/1953853', '孙扶摇/1953827', '钟凌云/1953828'],
 ['崔一鸣/1953110', '常培阳/1953635', '王宪聪/1952577', '益西志玛/1950803'],
 ['胡佳欣/1953201', '姜博/1950817', '郭佳昊/1952053'],
 ['王砚轩/1853823', '白羽禾/1852126', '谢亦凡/1851110'],
 ['贾敬伟/1952040', '毕维翰/1951738', '周慧萱/1953302', '刘雅天/1952250'],
 ['詹伟源/1951607', '李积瀚/1952042', '赵乾为/1951873'],
 ['刘釜静/1851832', '彭宇菲/1952182', '王瑞姝/1753856'],
 ['胡琼欣/1953631', '卓兆梁/1982923'],
 ['洪杉/1951251', '屈颖涛/1953924', '欧宏宇/1951152', '李子睿/1954107'],
 ['郭睿博/1952248', '王剑辉/1952934', '陶宁然/1952227'],
 [' 陈康捷/1853609', '曾妮/1853169 ', '徐傲/1853726', '陈鹏宇/1853687'],
 ['邓骞/1852823', '', '金筱语/1850926', '赫书瑶/1853252'],
 ['骆旅舟/1753125', '张凯乐/1750106', '赵新东/1751149'],
 ['孙奥/1851312', '', '王子涵/1850722', '李炜博/1850811', '', '', '项凯文/1850132'],
 ['赵志禹/1953754', '刘姝仪/1953940'],
 ['王之炫/1952589', '', '吴晨玮/1952554', '', '何汝欣/1953792', '', '史栩涛/1953599'],
 ['王晨杨/1852830', '朱林洁/1852553', '班辰1852324'],
 ['陈子杭/1953838', '杜墀/1952588', '傅钰杰/1952919', '刘学凯/1953114'],
 ['吴林轩/1850072', '', '闫新宇/1852128', '', '朱康/1852183', '', '施致远/1851688'],
 ['刘旭东/1852428', '罗冠培/1852544'],
 ['王瀚林/1953804',
  '',
  '',
  '',
  '李怡凡/1953598',
  '',
  '',
  '张羽/1953633',
  '',
  '',
  '郑焯文/1951710\t'],
 ['李洋旻/1953177', '何雨浓/1953175'],
 ['何唯屹/1951990', '', '', '成子涵/1952068', '', '仇明西/1953391'],
 ['杨溥炎/1850631', '', '', '', '', '张志昂/1854020'],
 ['香宁雨/1954098', '安江涛/1952560', '黄奕辰/1950003', '李璐/1951250'],
 ['郑志显/1851879', '', '王景业/1754228'],
 ['胡绮芮/1953403', '李耘畅/1952139'],
 ['白亚坤/1952243', '范文萱/1951508'],
 ['李金禾/1852431', '韩笑/1854047']]

In [8]:
len(a)

57

In [9]:
name=[]
xuehao=[]
for i in range(len(a)):
    name_i=[]
    xuehao_i=[]
    name_i.append(df_1['负责人姓名'][i])
    xuehao_i.append(df_1['负责人学号'][i])
    for j in a[i]:
        if len(j)>2:
            #print(j)
            xuehao_i.append(j[-7:])
            if '/' in j:
                name_i.append(j[:-8])
            else:
                name_i.append(j[:-7])
    name.append(name_i)
    xuehao.append(xuehao_i)

In [10]:
name

[['陈宇', '冯翊', '刘帅年'],
 ['陈树', '寇蓝文', '王乐'],
 ['李兆祥', '汪诗雨', '魏鹏程'],
 ['张雪晨', '刘裕行', '赵启晨'],
 ['陈明韬', '刘天元', '闫弘'],
 ['刘岳朋', '张笑寒', '尹长江'],
 ['何志扬', '周鹏', '肖启贤'],
 ['刘诣烜', '姚永锐', '徐晨龙'],
 ['汪芷瑶', '陈璟赋', '孙思薇'],
 ['曹耒', '郭子淳'],
 ['聂通', '刘佳明', '黄健'],
 ['韦海云', '张露颖', '周家旋'],
 ['梁星', '王思澄', '袁宇童'],
 ['王皓月', '樊庶', '代贵淇'],
 ['杨帆', '周思琪', '杨雨辰'],
 ['张英杰', '潘帅鑫', '汤兆年'],
 ['付诚', '曾宪坤', '姜梓恒'],
 ['苏浩文', '徐子璇', '吴子豪'],
 ['董楚阳', '余宁海', '张荣添', '梁雨萌'],
 ['劳欣芸', '胡启云', '钱璟怡'],
 ['李卓伦', '张子阳', '韦欢夏', '沈梦竹', '尹天硕'],
 ['孙源辰', '唐一淼', '唐宇瀚', '江宇睿', '王雨悦'],
 ['武一丹', '陶冶', '齐晓燕', '蓝天'],
 ['龚正', '许灵辰', '张家瑞', '刘思睿', '李心瑜'],
 ['陈昀健', '岳钊名', '卞宇轩', '李涛', '孙涵枫'],
 ['段志煜', '王子玮', '杨逢春', '郭浩'],
 ['多吉战都', '加旺顿珠', '格桑', '萨米那', '格桑曲珍'],
 ['冯不凡', '', '胡逸凡', '柏成'],
 ['何其真', '董泽坤', '彭西哿', '孙扶摇', '钟凌云'],
 ['李思平', '崔一鸣', '常培阳', '王宪聪', '益西志玛'],
 ['刘璨', '胡佳欣', '姜博', '郭佳昊'],
 ['王卓非', '王砚轩', '白羽禾', '谢亦凡'],
 ['夏凡钰', '贾敬伟', '毕维翰', '周慧萱', '刘雅天'],
 ['易晨歆', '詹伟源', '李积瀚', '赵乾为'],
 ['丁欣怡', '刘釜静', '彭宇菲', '王瑞姝'],
 ['郝一霖', '胡琼欣', '卓兆梁'],
 ['黄洁', '洪杉', '屈颖涛', '欧宏宇', '李子睿'],
 ['陶一豪', '郭睿博', '王剑辉', '陶宁然'],
 ['王炳钧', ' 陈康捷', '曾妮/', '徐傲', '陈鹏宇'],
 ['王俊勇', '邓骞', '金筱语', '赫书瑶'],
 ['王子达', '骆旅舟', '张凯乐', '赵新东'],
 ['彭远', '孙奥', '王子涵', '李炜博', '项凯文'],
 ['赵祥森', '赵志禹', '刘姝仪'],
 ['赵中宁', '王之炫', '吴晨玮', '何汝欣', '史栩涛'],
 ['段行言', '王晨杨', '朱林洁', '班辰'],
 ['何昶勇', '陈子杭', '杜墀', '傅钰杰', '刘学凯'],
 ['马杰', '吴林轩', '闫新宇', '朱康', '施致远'],
 ['马旭', '刘旭东', '罗冠培'],
 ['杨若瑜', '王瀚林', '李怡凡', '张羽', '郑焯文/'],
 ['赵亦悦', '李洋旻', '何雨浓'],
 ['任川', '何唯屹', '成子涵', '仇明西'],
 ['杨硕', '杨溥炎', '张志昂'],
 ['封钰震', '香宁雨', '安江涛', '黄奕辰', '李璐'],
 ['卢泽润', '郑志显', '王景业'],
 ['刘林坤', '胡绮芮', '李耘畅'],
 ['吝智杰', '白亚坤', '范文萱'],
 ['张远哲', '李金禾', '韩笑']]

In [187]:
str(xuehao)

"[[1852930, '1853850', '1851963'], [1851227, '1853010', '1851929'], [1851872, '1850847', '1850001'], [1854161, '1851608', '1851878'], [1850912, '1852971', '1852571'], [1850275, '1853501', '1850481'], [1850932, '1853854', '1853361'], [1853819, '1851876', '1854084'], [1851318, '1851175', '1854171'], [1852088, '1852089'], [1854361, '1851626', '1854190'], [1854129, '1853605', '1854127'], [1850933, '1853804', '1851615'], [1851390, '1850630', '1853453'], [1853765, '1853521', '1853829'], [1753330, '1752221', '1752063'], [1854081, '1852844', '1853102'], [1853447, '1853838', '1752066'], [1951103, '1951354', '1952541', '1953833'], [1952930, '1952897', '1952946'], [1953167, '1953437', '1953666', '1953248', '1953350'], [1951732, '1953210', '1950152', '1953197', '1950172'], [1951446, '1952066', '1953907', '1951609'], [1952367, '1954101', '1952241', '1953103', '1951242'], [1953106, '1953727', '1953927', '1953107', '1953955'], [1753545, '1753387', '1751913', '1853926'], [1754307, '1754297', '1754291', '1754288', '1754305'], [1750068, '1751148', '1753180', '1752157'], [1951790, '1953768', '1953853', '1953827', '1953828'], [1953635, '1953110', '1953635', '1952577', '1950803'], [1952764, '1953201', '1950817', '1952053'], [1850136, '1853823', '1852126', '1851110'], [1952039, '1952040', '1951738', '1953302', '1952250'], [1951739, '1951607', '1952042', '1951873'], [1854140, '1851832', '1952182', '1753856'], [1953100, '1953631', '1982923'], [1953307, '1951251', '1953924', '1951152', '1954107'], [1952247, '1952248', '1952934', '1952227'], [1853409, '1853609', '853169 ', '1853726', '1853687'], [1853987, '1852823', '1850926', '1853252'], [1754003, '1753125', '1750106', '1751149'], [1852526, '1851312', '1850722', '1850811', '1850132'], [1953732, '1953754', '1953940'], [1952574, '1952589', '1952554', '1953792', '1953599'], [1852435, '1852830', '1852553', '1852324'], [1952774, '1953838', '1952588', '1952919', '1953114'], [1852941, '1850072', '1852128', '1852183', '1851688'], [1852885, '1852428', '1852544'], [1953583, '1953804', '1953598', '1953633', '951710\\t'], [1952430, '1953177', '1953175'], [1950933, '1951990', '1952068', '1953391'], [1850558, '1850631', '1854020'], [1951362, '1954098', '1952560', '1950003', '1951250'], [1851540, '1851879', '1754228'], [1952431, '1953403', '1952139'], [1952421, '1952243', '1951508'], [1854023, '1852431', '1854047']]"

In [188]:
name_new=[]
xuehao_new=[]
for i in range(len(xuehao)):
    x=xuehao[i]
    y=name[i]
    xuehao_i=''
    name_i=''
    for j in range(len(x)):
        xuehao_i=xuehao_i+str(x[j])+','
        name_i=name_i+str(y[j])+','
    name_new.append(name_i)
    xuehao_new.append(xuehao_i)

In [13]:
name_new1=[]
xuehao_new1=[]
for i in range(len(xuehao)):
    x=xuehao[i]
    y=name[i]
    for j in range(len(x)):
        name_new1.append(y[j])
        xuehao_new1.append(x[j])

In [15]:
xuehao_new1

[1852930,
 '1853850',
 '1851963',
 1851227,
 '1853010',
 '1851929',
 1851872,
 '1850847',
 '1850001',
 1854161,
 '1851608',
 '1851878',
 1850912,
 '1852971',
 '1852571',
 1850275,
 '1853501',
 '1850481',
 1850932,
 '1853854',
 '1853361',
 1853819,
 '1851876',
 '1854084',
 1851318,
 '1851175',
 '1854171',
 1852088,
 '1852089',
 1854361,
 '1851626',
 '1854190',
 1854129,
 '1853605',
 '1854127',
 1850933,
 '1853804',
 '1851615',
 1851390,
 '1850630',
 '1853453',
 1853765,
 '1853521',
 '1853829',
 1753330,
 '1752221',
 '1752063',
 1854081,
 '1852844',
 '1853102',
 1853447,
 '1853838',
 '1752066',
 1951103,
 '1951354',
 '1952541',
 '1953833',
 1952930,
 '1952897',
 '1952946',
 1953167,
 '1953437',
 '1953666',
 '1953248',
 '1953350',
 1951732,
 '1953210',
 '1950152',
 '1953197',
 '1950172',
 1951446,
 '1952066',
 '1953907',
 '1951609',
 1952367,
 '1954101',
 '1952241',
 '1953103',
 '1951242',
 1953106,
 '1953727',
 '1953927',
 '1953107',
 '1953955',
 1753545,
 '1753387',
 '1751913',
 '1853926',
 1754307,
 '1754297',
 '1754291',
 '1754288',
 '1754305',
 1750068,
 '1751148',
 '1753180',
 '1752157',
 1951790,
 '1953768',
 '1953853',
 '1953827',
 '1953828',
 1953635,
 '1953110',
 '1953635',
 '1952577',
 '1950803',
 1952764,
 '1953201',
 '1950817',
 '1952053',
 1850136,
 '1853823',
 '1852126',
 '1851110',
 1952039,
 '1952040',
 '1951738',
 '1953302',
 '1952250',
 1951739,
 '1951607',
 '1952042',
 '1951873',
 1854140,
 '1851832',
 '1952182',
 '1753856',
 1953100,
 '1953631',
 '1982923',
 1953307,
 '1951251',
 '1953924',
 '1951152',
 '1954107',
 1952247,
 '1952248',
 '1952934',
 '1952227',
 1853409,
 '1853609',
 '853169 ',
 '1853726',
 '1853687',
 1853987,
 '1852823',
 '1850926',
 '1853252',
 1754003,
 '1753125',
 '1750106',
 '1751149',
 1852526,
 '1851312',
 '1850722',
 '1850811',
 '1850132',
 1953732,
 '1953754',
 '1953940',
 1952574,
 '1952589',
 '1952554',
 '1953792',
 '1953599',
 1852435,
 '1852830',
 '1852553',
 '1852324',
 1952774,
 '1953838',
 '1952588',
 '1952919',
 '1953114',
 1852941,
 '1850072',
 '1852128',
 '1852183',
 '1851688',
 1852885,
 '1852428',
 '1852544',
 1953583,
 '1953804',
 '1953598',
 '1953633',
 '951710\t',
 1952430,
 '1953177',
 '1953175',
 1950933,
 '1951990',
 '1952068',
 '1953391',
 1850558,
 '1850631',
 '1854020',
 1951362,
 '1954098',
 '1952560',
 '1950003',
 '1951250',
 1851540,
 '1851879',
 '1754228',
 1952431,
 '1953403',
 '1952139',
 1952421,
 '1952243',
 '1951508',
 1854023,
 '1852431',
 '1854047']

In [16]:
dic1={'学号':xuehao_new1,'姓名':name_new1}
df_2=pd.DataFrame(dic1)
df_2

          学号   姓名
0    1852930   陈宇
1    1853850   冯翊
2    1851963  刘帅年
3    1851227   陈树
4    1853010  寇蓝文
..       ...  ...
210  1952243  白亚坤
211  1951508  范文萱
212  1854023  张远哲
213  1852431  李金禾
214  1854047   韩笑

[215 rows x 2 columns]

In [17]:
tpath=r'C:\Users\刘佳琦\Desktop\导出.xlsx'
df_2.to_excel(tpath)